/* GWBASIC Tokens */
/* Include this file in your associative array. */
/* If you need to edit the tokens, this is where you do it. */
{0x81, "END"},
{0x82, "FOR"},
{0x83, "NEXT"},
{0x84, "DATA"},
{0x85, "INPUT"},
{0x86, "DIM"},
{0x87, "READ"},
{0x88, "LET"},
{0x89, "GOTO"},
{0x8a, "RUN"},
{0x8b, "IF"},
{0x8c, "RESTORE"},
{0x8d, "GOSUB"},
{0x8e, "RETURN"},
{0x8f, "REM"},
{0x90, "STOP"},
{0x91, "PRINT"},
{0x92, "CLEAR"},
{0x93, "LIST"},
{0x94, "NEW"},
{0x95, "ON"},
{0x96, "WAIT"},
{0x97, "DEF"},
{0x98, "POKE"},
{0x99, "CONT"},
{0x9a, "(Undefined)"},
{0x9b, "(Undefined)"},
{0x9c, "OUT"},
{0x9d, "LPRINT"},
{0x9e, "LLIST"},
{0x9f, "(Undefined)"},
{0xa0, "WIDTH"},
{0xa1, "ELSE"},		// stored as 3AA1, ":ELSE" but the ":" is suppressed when the program is listed.
{0xa2, "TRON"},
{0xa3, "TROFF"},
{0xa4, "SWAP"},
{0xa5, "ERASE"},
{0xa6, "EDIT"},
{0xa7, "ERROR"},
{0xa8, "RESUME"},
{0xa9, "DELETE"},
{0xaa, "AUTO"},
{0xab, "RENUM"},
{0xac, "DEFSTR"},
{0xad, "DEFINT"},
{0xae, "DEFSNG"},
{0xaf, "DEFDBL"},
{0xb0, "LINE"},
{0xb1, "WHILE"},	// stored as B1E9, "WHILE+" but the "+" is suppressed when the program is listed.
{0xb2, "WEND"},
{0xb3, "CALL"},
{0xb4, "(Undefined)"},
{0xb5, "(Undefined)"},
{0xb6, "(Undefined)"},
{0xb7, "WRITE"},
{0xb8, "OPTION"},
{0xb9, "RANDOMIZE"},
{0xba, "OPEN"},
{0xbb, "CLOSE"},
{0xbc, "LOAD"},
{0xbd, "MERGE"},
{0xbe, "SAVE"},
{0xbf, "COLOR"},
{0xc0, "CLS"},
{0xc1, "MOTOR"},
{0xc2, "BSAVE"},
{0xc3, "BLOAD"},
{0xc4, "SOUND"},
{0xc5, "BEEP"},
{0xc6, "PSET"},
{0xc7, "PRESET"},
{0xc8, "SCREEN"},
{0xc9, "KEY"},
{0xca, "LOCATE"},
{0xcb, "(Undefined)"},
{0xcc, "TO"},
{0xcd, "THEN"},
{0xce, "TAB("},	// note that the following "(" is part of the keyword with no intervening space. That's why "TAB   (..." will not work.
{0xcf, "STEP"},
{0xd0, "USR"},
{0xd1, "FN"},
{0xd2, "SPC("},	// note that the following "(" is part of the keyword with no intervening space. That's why "SPC   (..." will not work.
{0xd3, "NOT"},
{0xd4, "ERL"},
{0xd5, "ERR"},
{0xd6, "STRING$"},
{0xd7, "USING"},
{0xd8, "INSTR"},
{0xd9, "'"},	// stored as 3A8FD9, ":REM'" but the ":REM" is suppressed when the program is listed.
{0xda, "VARPTR"},
{0xdb, "CSRLIN"},
{0xdc, "POINT"},
{0xdd, "OFF"},
{0xde, "INKEY$"},
{0xdf, "(Undefined)"},
{0xe0, "(Undefined)"},
{0xe1, "(Undefined)"},
{0xe2, "(Undefined)"},
{0xe3, "(Undefined)"},
{0xe4, "(Undefined)"},
{0xe5, "(Undefined)"},
{0xe6, ">"},
{0xe7, "="},
{0xe8, "<"},
{0xe9, "+"},
{0xea, "-"},
{0xeb, "*"},
{0xec, "/"},
{0xed, "^"},
{0xee, "AND"},
{0xef, "OR"},
{0xf0, "XOR"},
{0xf1, "EQV"},
{0xf2, "IMP"},
{0xf3, "MOD"},
{0xf4, "\\"},
{0xf5, "(Undefined)"},
{0xf6, "(Undefined)"},
{0xf7, "(Undefined)"},
{0xf8, "(Undefined)"},
{0xf9, "(Undefined)"},
{0xfa, "(Undefined)"},
{0xfb, "(Undefined)"},
{0xfc, "(Undefined)"},

// Two-byte tokens.
{0xfd81, "CVI"},
{0xfd82, "CVS"},
{0xfd83, "CVD"},
{0xfd84, "MKI$"},
{0xfd85, "MKS$"},
{0xfd86, "MKD$"},
{0xfd8b, "EXTERR"},
{0xfe81, "FILES"},
{0xfe82, "FIELD"},
{0xfe83, "SYSTEM"},
{0xfe84, "NAME"},
{0xfe85, "LSET"},
{0xfe86, "RSET"},
{0xfe87, "KILL"},
{0xfe88, "PUT"},
{0xfe89, "GET"},
{0xfe8a, "RESET"},
{0xfe8b, "COMMON"},
{0xfe8c, "CHAIN"},
{0xfe8d, "DATE$"},
{0xfe8e, "TIME$"},
{0xfe8f, "PAINT"},
{0xfe90, "COM"},
{0xfe91, "CIRCLE"},
{0xfe92, "DRAW"},
{0xfe93, "PLAY"},
{0xfe94, "TIMER"},
{0xfe95, "ERDEV"},
{0xfe96, "IOCTL"},
{0xfe97, "CHDIR"},
{0xfe98, "MKDIR"},
{0xfe99, "RMDIR"},
{0xfe9a, "SHELL"},
{0xfe9b, "ENVIRON"},
{0xfe9c, "VIEW"},
{0xfe9d, "WINDOW"},
{0xfe9e, "PMAP"},
{0xfe9f, "PALETTE"},
{0xfea0, "LCOPY"},
{0xfea1, "CALLS"},

#ifdef PCJR
	{0xfea4, "NOISE"},
#elif SPERRY
	{0xfea4, "DEBUG"},
#else
	{0xfea4, "(Undefined)"},
#endif

{0xfea5, "PCOPY"},

#ifdef PCJR
	{0xfea6, "TERM"},
#else
	{0xfea6, "(Undefined)"},
#endif

{0xfea7, "LOCK"},
{0xfea8, "UNLOCK"},
{0xff81, "LEFT$"},
{0xff82, "RIGHT$"},
{0xff83, "MID$"},
{0xff84, "SGN"},
{0xff85, "INT"},
{0xff86, "ABS"},
{0xff87, "SQR"},
{0xff88, "RND"},
{0xff89, "SIN"},
{0xff8a, "LOG"},
{0xff8b, "EXP"},
{0xff8c, "COS"},
{0xff8d, "TAN"},
{0xff8e, "ATN"},
{0xff8f, "FRE"},
{0xff90, "INP"},
{0xff91, "POS"},
{0xff92, "LEN"},
{0xff93, "STR$"},
{0xff94, "VAL"},
{0xff95, "ASC"},
{0xff96, "CHR$"},
{0xff97, "PEEK"},
{0xff98, "SPACE$"},
{0xff99, "OCT$"},
{0xff9a, "HEX$"},
{0xff9b, "LPOS"},
{0xff9c, "CINT"},
{0xff9d, "CSNG"},
{0xff9e, "CDBL"},
{0xff9f, "FIX"},
{0xffa0, "PEN"},
{0xffa1, "STICK"},
{0xffa2, "STRIG"},
{0xffa3, "EOF"},
{0xffa4, "LOC"},
{0xffa5, "LOF"},

// These aren't "official", but included here to make life easier.
// The point of these is that GW modifies the output anyway and pretty much just throws away the extra stuff.
{0x3aa1, "ELSE"},	// stored as 3AA1, ":ELSE" but the ":" is suppressed when the program is listed.
{0xb1e9, "WHILE"},	// stored as B1E9, "WHILE+" but the "+" is suppressed when the program is listed.
{0x3a8fd9,"'"},		// stored as 3A8FD9, ":REM'" but the ":REM" is suppressed when the program is listed.
